apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: image-processor-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-processor-deployment
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 15
  cooldownPeriod: 30
  triggers:
    - type: gcp-pubsub
      authenticationRef:
        name: gcp-credentials
      metadata:
        subscriptionSize: "5"
        subscriptionName: image-processing-queue-sub
        mode: SubscriptionSize