apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: image-processor-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-processor-deployment
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 15
  cooldownPeriod: 30
  triggers:
    - type: gcp-pubsub
      metadata:
        mode: SubscriptionSize
        value: "5"
        subscriptionName: image-processing-queue-sub
        projectId: dcsc-project-440602
        credentialsFromEnv: GOOGLE_APPLICATION_CREDENTIALS
        identityOwner: pod